car_service/car_service/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('service/', include('service.urls')),
    path('user_profile/', include('user_profile.urls', namespace='user_profile')),
    path('', RedirectView.as_view(url='service/', permanent=True)),

)

car_service/service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    path('', views.index, name='index'),

    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),

    path('car_instances/', views.CarInstanceListView.as_view(), name='car-instances'),
    path('car_instances/<int:pk>', views.CarInstanceDetailView.as_view(),
         name='car-instance-detail'),
    path('car_instances/search/', views.search_cars, name='car-instance-search'),
    path('orders/new/', views.CreateOrderView.as_view(), name='create-order'),
    path('orders/<int:pk>/update/',
         views.UpdateOrderView.as_view(), name='update-order'),
    path('orders/<int:pk>/delete/',
         views.DeleteOrderView.as_view(), name='delete-order'),

]

car_service/user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),

]

car_service/service/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import date, timedelta
from PIL import Image
from tinymce.models import HTMLField


# Create your models here.

class CarModel(models.Model):
    make = models.CharField(_('Make'), max_length=50, null=False, help_text=_(
        'Car manufacturer'), db_index=True)
    model = models.CharField(_('Model'), max_length=50, null=False, help_text=_(
        'Car model'), db_index=True)

    class Meta:
        ordering = ['make', 'model']
        verbose_name = _('Car Model')
        verbose_name_plural = _('Car Models')

    def __str__(self) -> str:
        return f'{self.make} {self.model}'


class CarInstance(models.Model):
    registration = models.CharField(
        _('Registration'), max_length=6, null=False, db_index=True)
    vin = models.CharField(_('VIN'), max_length=17, null=False, db_index=True)
    model = models.ForeignKey(
        CarModel,
        null=False,
        on_delete=models.CASCADE,
        verbose_name=_("Car Model"),
        related_name='car_instances',
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              null=False, on_delete=models.CASCADE)
    picture = models.ImageField(
        _('Picture'), default='service/img/default.png')
    description = HTMLField(
        _('Description'), max_length=10000, blank=True, default='')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self. picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.picture.path)

    class Meta:
        verbose_name = _('Car Instance')
        verbose_name_plural = _('Car Instances')

    def __str__(self) -> str:
        return f'{self.model} {self.registration}'


class Order(models.Model):
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    car_instance = models.ForeignKey(
        CarInstance,
        null=False,
        on_delete=models.CASCADE,
        verbose_name=_("Car Instance"),
        related_name='orders',
    )
    sum = models.DecimalField(_('Sum'), null=True, blank=True, default=0,
                              max_digits=10, decimal_places=2)

    ORDER_STATUS = (
        (0, _("New")),
        (10, _("Working")),
        (20, _("Finished repairs")),
        (30, _("Closed (paid)")),
        (50, _("Removed")),
    )

    status = models.PositiveIntegerField(
        _('Status'), default=0, choices=ORDER_STATUS)

    due_back = models.DateField(
        _('Due back'), null=True, blank=True, default=date.today() + timedelta(days=7))

    @property
    def is_overdue(self):
        if self.status >= 0 and self.status <= 30 and self.due_back and self.due_back < date.today():
            return True
        return False

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self) -> str:
        return f'{self.car_instance}: {self.created_at} - {self.sum}'


class Service(models.Model):
    name = models.CharField(_('Name'), max_length=50,
                            null=False, db_index=True)
    price = models.DecimalField(
        _('Price'), null=False, max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self) -> str:
        return f'{self.name}: {self.price}'


class OrderLine(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        on_delete=models.CASCADE,
        verbose_name=_("Order"),
        related_name='order_lines',
    )
    service = models.ForeignKey(
        Service,
        null=False,
        on_delete=models.CASCADE,
        verbose_name=_("Service"),
        related_name='order_lines',
    )
    quantity = models.PositiveIntegerField(_('Quantity'), null=False)
    price = models.DecimalField(
        _('Price'), null=False, max_digits=10, decimal_places=2)

    @property
    def total_price(self):
        total_price = self.price * self.quantity
        return total_price

    class Meta:
        verbose_name = _('Order Line')
        verbose_name_plural = _('Orders Lines')

    def __str__(self) -> str:
        return f'{self.service.name}: {self.price}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.order.sum = 0
        for line in self.order.order_lines.all():
            self.order.sum += line.total_price
        self.order.save()


class OrderMessages(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        on_delete=models.CASCADE,
        verbose_name=_("Order"),
        related_name='order_messages',
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=False,
        on_delete=models.CASCADE)
    message = HTMLField(_('Message'), max_length=1000, blank=True, default='')
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)

    class Meta:
        verbose_name = _('Order Message')
        verbose_name_plural = _('Order Messages')

    def __str__(self) -> str:
        return f'{self.order}, {self.author}: {self.message}'

car_service/service/forms.py
from django import forms
from .models import Order, OrderMessages, CarInstance


class OrderMessageForm(forms.ModelForm):
    class Meta:
        model = OrderMessages
        fields = ('order', 'author', 'message',)
        widgets = {
            'order': forms.HiddenInput(),
            'author': forms.HiddenInput(),
            'message': forms.Textarea(attrs={"cols": "50", "rows": "3", "style": "width:100%;"},),
        }


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('car_instance', 'due_back')
        widgets = {
            'car_instance': forms.Select(),
            'due_back': forms.DateInput(),
        }

    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the current user
        are given as options"""

        self.request = kwargs.pop('request')
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['car_instance'].queryset = CarInstance.objects.filter(
            owner=self.request.user)

car_service/service/views.py
from datetime import date, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views import generic
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from .models import CarModel, CarInstance, Service, Order
from .forms import OrderMessageForm, OrderForm


# Create your views here.


def index(request):
    num_models = CarModel.objects.count()
    num_car_instances = CarInstance.objects.count()
    num_services = Service.objects.count()
    num_orders_completed = Order.objects.filter(status__exact=30).count()
    num_visits = int(request.session.get('num_visits', 0)) + 1
    request.session['num_visits'] = num_visits

    context = {
        'num_models': num_models,
        'num_car_instances': num_car_instances,
        'num_services': num_services,
        'num_orders_completed': num_orders_completed,
        'num_visits': num_visits,
    }
    return render(request, 'service/index.html', context=context)


class CarInstanceListView(LoginRequiredMixin, generic.ListView):
    model = CarInstance
    template_name = 'service/car_instance_list.html'
    context_object_name = 'car_instances'
    queryset = CarInstance.objects.all()
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class CarInstanceDetailView(generic.DetailView):
    model = CarInstance
    context_object_name = 'car_instance_detail'
    template_name = 'service/car_instance_detail.html'

    def get_success_url(self):
        return reverse_lazy('service:car-instance-detail', kwargs={'pk': self.object.id})


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'service/order_list.html'
    context_object_name = 'orders'
    queryset = Order.objects.all()
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            queryset = queryset.filter(car_instance__owner=self.request.user)
        return queryset


class OrderDetailView(generic.DetailView, FormMixin):
    model = Order
    context_object_name = 'order'
    template_name = 'service/order_detail.html'
    form_class = OrderMessageForm

    def get_success_url(self):
        return reverse_lazy('service:order-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderMessageForm(initial={
            'order': self.object,
            'author': self.request.user
        })
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.author = self.request.user
        form.save()
        return super(OrderDetailView, self).form_valid(form)


class CreateOrderView(generic.CreateView, LoginRequiredMixin):
    model = Order
    # fields = ['car_instance', 'due_back', ]
    success_url = reverse_lazy('service:orders')
    template_name = 'service/order_form.html'
    form_class = OrderForm

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'due_back': date.today() + timedelta(days=7)
        })
        return initial

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(CreateOrderView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class UpdateOrderView(generic.UpdateView, LoginRequiredMixin):
    model = Order
    # fields = ['car_instance', 'due_back', ]
    success_url = reverse_lazy('service:orders')
    template_name = 'service/order_form.html'
    form_class = OrderForm

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(UpdateOrderView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.car_instance.owner


class DeleteOrderView(generic.DeleteView, LoginRequiredMixin):
    model = Order
    success_url = reverse_lazy('service:orders')
    template_name = 'service/order_delete.html'

    def test_func(self):
        order = self.get_object()
        return self.request.user == order.car_instance.owner


def search_cars(request):
    query = request.GET.get('query')
    search_results = CarInstance.objects.filter(
        Q(model__model__icontains=query) |
        Q(owner__first_name__icontains=query) |
        Q(owner__last_name__icontains=query) |
        Q(registration__icontains=query) |
        Q(vin__icontains=query)
    )
    context = {
        'cars': search_results,
        'query': query
    }
    return render(request, 'service/search_cars.html', context=context)

car_service/service/templates/service/base.html
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load i18n %}
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'service/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <title>{% block title %}{% trans 'Car Service' %}{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% block navigation %}
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'service:index' %}">{% trans 'Home' %}</a></li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'user_profile:profile' %}">{% trans 'My Profile' %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'service:car-instances' %}">{% trans 'Cars' %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'service:orders' %}">{% trans 'Orders' %}</a></li>

                {% if request.user.is_superuser or request.user.is_staff %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                {% endif %}
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={% url 'service:index' %}">{% trans 'Logout' %}</a></li>
            <li class="nav-item"><div class="my-2 my-md-0 p-2">
                <p>{% if request.user.first_name %}{{ request.user.first_name }}{% else %}{{ request.user.get_username }}{% endif %}</p>
            </div></li>
            <li class="nav-item">
                <form action="{% url 'service:car-instance-search' %}" method="get" class="form-inline- my-2 my-md-0">
                    <input type="text" name="query" class="form-control" placeholder="{% trans 'Search' %}">
                </form>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={{request.path}}">{% trans 'Login' %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'user_profile:register' %}">{% trans 'Register' %}</a></li>
            {% endif %}
            <li class="nav-item">
                <form action="{% url 'set_language' %}" method="post" class="form-inline- my-2 my-md-0 p-2">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ request.path }}">
                    <select name="language" onchange="this.form.submit()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected="selected"{% endif %}>{{ language.name_local }}</option>
                    {% endfor %}
                    </select>
                </form>
            </li>
        </ul>
        {% endblock navigation %}
        </div>
    </nav>
    <div class="container">
        {% block messages %}
            {% if messages %}
                {% for message in messages%}
                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endblock messages %}

        {% block content %}{% endblock content %}
        {% if debug %}{% block debug %}
        <div class="debug">{{ debug }}</div>
        {% endblock debug %}{% endif %}
    </div>        
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

car_service/service/templates/service/car_instance_detail.html
{% extends 'service/base.html' %}
{% load i18n static %}

{% block content %}
<section>
    <h1>{{ car_instance_detail.registration }}</a> - {{ car_instance_detail.model }}</h1>
    <img class="rounded-square account-img" src="
    {% if car_instance_detail.picture %}
        {{ car_instance_detail.picture.url }}
    {% else %}
        {% static 'service/img/default.png' %}
    {% endif %}">
    <p>{% trans 'Description' %}: {{ car_instance_detail.description|safe }}</p>
    <p>{% trans 'Owner' %}: {% if car_instance_detail.owner.first_name %}{{ car_instance_detail.owner.first_name }} {{ car_instance_detail.owner.last_name }}{% else %}{{ car_instance_detail.owner }}{% endif %}</p>
    <p>{% trans 'VIN' %}: {{ car_instance_detail.vin }}</p>
</section>

{% endblock content %}

car_service/service/templates/service/car_instance_list.html
{% extends 'service/base.html' %}
{% load i18n static %}

{% block content %}
    <h1>{% trans "Car instance list" %}</h1>
    {% if car_instances %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous%}
                <a href="?page=1">{% trans 'first' %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}
            <span class="current"> {{page_obj.number}} {% trans 'of' %} {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_next%}
                <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'last' %}</a>
            {% endif %}
        </span>
    </div>
    <div class="row">
        {% for car_instance in car_instances %}
            <div class="col-md-4 d-flex align-items-stretch">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" src="
                    {% if car_instance.picture %}
                        {{ car_instance.picture.url }}
                    {% else %}
                        {% static 'service/img/default.png' %}
                    {% endif %}">
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2"> <a href="{% url 'service:car-instance-detail' car_instance.id %}">{{ car_instance.registration }}</a> - {{ car_instance.model }}</h6>
                        <p class="card-text mb-1">{% trans 'Owner' %}: {{ car_instance.owner }}</p>
                        <p class="card-text mb-0">{% trans 'VIN' %}: {{ car_instance.vin }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <p>{% trans "there are no cars registered in this car service" %}</p>
    {% endif %}
{% endblock content %}

car_service/service/templates/service/index.html
{% extends 'service/base.html' %}
{% load i18n %}

{% block content %}

<section>
    <ul class="list-group">
        <li class="list-group-item">{% trans 'Total Models' %}: {{ num_models }}</li>
        <li class="list-group-item">{% trans 'Total Car Instances' %}: {{ num_car_instances }}</li>
        <li class="list-group-item">{% trans 'Total Services Available' %}: {{ num_services }}</li>
        <li class="list-group-item">{% trans 'Total Orders Completed' %}: {{ num_orders_completed }}</li>
        <li class="list-group-item">{% trans 'Number of Your visits' %}: {{ num_visits }}</li>
    </ul>
</section>


{% endblock content %}

car_service/service/templates/service/order_delete.html
{% extends 'service/base.html' %}
{% load i18n crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{% trans 'delete this order' %}{{ object.car_instance }} | Due back: {{ object.due_back }}</legend>
            {% trans 'are you sure you want to delete this order' %} {{ object.car_instance }} | Due back: {{ object.due_back }}?
        </fieldset>
        <div class="form-group">
            <button class="btn btn-danger" type="submit">{% trans 'DELETE' %}</button>
            <a href="{% url 'service:orders' %}" class="btn btn-secondary">{% trans 'return to my orders' %}</a>
        </div>
    </form>
</div>
{% endblock content %}

car_service/service/templates/service/order_detail.html
{% extends 'service/base.html' %}
{% load i18n static %}

{% block content %}
<section>
    <h1>{{ order.car_instance }}</h1>
    <p>{% trans 'Order date' %}: {{ order.created_at }}</p>
    <p class="{% if order.is_overdue %}alert-danger{% endif %}">{% trans 'Due back' %}: {{ order.due_back }}</p>
    <p>{% trans 'Sum' %}: {{ order.sum }} EUR</p>

{% if order.order_lines %}
<ul class="list-group">
    {% for order_line in order.order_lines.all %}
        <li class="list-group-item">
            {% trans 'Service' %}: {{order_line.service.name}}, {% trans 'Count' %}: {{order_line.quantity}}, {% trans 'Price' %}: {{order_line.price}} EUR
        </li>
    {% endfor %}
</ul>
{% endif %}
</section>
<section>
{% if order.order_messages %}
<h4 class="mt-4">Messages</h4>
<ul class="list-group">
    {% for message in order.order_messages.all %}
        <li class="list-group-item">
            <h6>{% if message.author.first_name %}{{ message.author.first_name }} {{ message.author.last_name }}{% else %}{{ message.author }}{% endif %} on {{message.created_at}} wrote:</h6>
            {{message.message|safe}}
        </li>
    {% endfor %}
</ul>
{% endif %}
<div class="text-danger">{{ form.errors}}</div>
{% if request.user.is_authenticated and request.user == order.car_instance.owner%}
<div class="fieldWrapper">
    <h5>{% trans 'Leave your message' %}</h5>
    <form action="" method="post">
        {% csrf_token %}
        {{form.order}}
        {{form.author}}
        {{form.message}}
        <br>
        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-primary">
    </form>
</div>
{% endif %}
</section>

{% endblock content %}

car_service/service/templates/service/order_form.html
{% extends 'service/base.html' %}
{% load i18n crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{% trans 'Repair order for car' %}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">{% trans 'Save' %}</button>
            <a href="{% url 'service:orders' %}" class="btn btn-secondary">{% trans 'return to my orders' %}</a>
        </div>
    </form>
</div>
{% endblock content %}

car_service/service/templates/service/order_list.html
{% extends 'service/base.html' %}
{% load i18n static %}

{% block content %}
    <h1>{% trans "Order list" %}</h1>
    {% if orders %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous%}
                <a href="?page=1">{% trans 'first' %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}
            <span class="current"> {{page_obj.number}} {% trans 'of' %} {{ page_obj.paginator.num_pages }}</span>
            {% if page_obj.has_next%}
                <a href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'last' %}</a>
            {% endif %}
        </span>
    </div>
    <ul class="list-group">
        {% for order in orders %}
            <li class="list-group-item {% if order.is_overdue %}list-group-item-danger{% endif %}">
                <img src="{% if order.car_instance.owner and order.car_instance.owner.profile.picture %}{{ order.car_instance.owner.profile.picture.url }}{% else %}{% static 'user_profile/img/default.png' %}{% endif %}" class="rounded mr-2" style="max-height: 70px">
                <a href="{% url 'service:order-detail' order.id %}" style="height: 2rem">{{ order.car_instance }} | Due back: {{ order.due_back }}</a>
                {% if order.car_instance.owner == request.user %}
                <a href="{% url 'service:update-order' order.id %}" class="btn btn-info">{% trans 'Update' %}</a>
                <a href="{% url 'service:delete-order' order.id %}" class="btn btn-danger">{% trans 'Delete' %}</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>{% trans "there are no orders registered in this car service" %}</p>
    {% endif %}
    <a href="{% url 'service:create-order'%}" class="btn btn-primary mt-2">{% trans 'Place order' %}</a>
{% endblock content %}

car_service/service/templates/service/search_cars.html
{% extends 'service/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Search results' %}</h1>
<p>{% trans 'Query' %}: <span class="text-bold">{{ query }}</span></p>
    {% if cars %}
    <ul class="list-group">
    {% for car in cars %}
        <li class="list-group-item">
        <a href="{% url 'service:car-instance-detail' car.id %}">{{ car }}</a>
        </li>
    {% endfor %}
    {%else%}
    <p class="text-danger">{% trans 'no matches found' %}</p>
    </ul>
    {%endif%}

{% endblock content %}